const appname = "eMart";
const appversion = "Version 1.0.0";
const credits = "@Shamim Dev";
const email = "Email";
const emailHint = "admin@gmail.com";
const password = "Password";
const passwordHint = "******";
const forgetpass = "forget password";
const retypePassword = "Retype Password";
const name = "Name";
const nameHint = "Shamim Dev";
const login = "Log in";
const signup = "Sign up";
const createNewAccount = "or,create a new account";
const loginWith = "Log in with";
const privacyPolicy = "Privacy Policy";
const termAndCond = "Terms and Conditions";
const alreadyHaveAccount = "Already have a account?";
const home = "Home",
    categories = "Categories",
    cart = "Cart",
    account = "Account";
const searchanything = "Search Anything..",
    todayDeal = "Today Deals",
    flashsale = "Flash Sale",
    topSeller = "Top Sellers",
    brand = "Brand",
    topcategories = "Top Categories",
    womandress = "Woman Dress",
    girlswatch = "Girls Watch",
    mobilephone = "Mobile Phone",
    boysglasses = "Boys Glasses",
    tshirts = "T Shairts",
    girlsdress = "Girls Dress",
    featuredproduct = "Featured Product",
    fuaturedcategories = "Fuatured Categories";

const womanclothing = "Woman Clothing";
const manclothing = "Man Clothing";
const comaccess = "Computer Access";
const automobile = "Auto Mobile";
const kidstoy = "Kids Toy";
const sports = "Sports";
const jewellery = "Jewellery";
const cellphone = "CellPhone&Tabs";
const furniture = "Furniture";
